# fly.toml app configuration file generated for monument-to-stupidity-db on 2023-05-06T22:10:29+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "monument-to-stupidity-db"
primary_region = "lhr"

[build]
  dockerfile = "pb.dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"
